services:
  # to allow access via local DNS
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - tao_network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  tao_nginx:
    container_name: tao_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`tao.localhost`)"
      - "traefik.http.services.mywhoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.entrypoints=web"
    image: nginx:stable
    networks:
      - tao_network
    ports:
      - "8085:80"
    volumes_from:
      - tao_phpfpm
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d

  tao_phpfpm_base:
    image: local/phpfpm:latest
    build:
      context: ./docker/phpfpm
    entrypoint: ["echo", "Base image only"]

  tao_phpfpm:
    container_name: tao_phpfpm
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    expose:
      - 9000
    networks:
      - tao_network
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html

  tao_db:
    container_name: tao_db
    image: mariadb:latest
    networks:
      - tao_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_USER: tao
      MYSQL_PASSWORD: tao
      MYSQL_DATABASE: tao
    volumes:
      - tao_mariadb_data:/var/lib/mysql:cached

volumes:
  tao_mariadb_data:
    driver: local

networks:
  tao_network:
    driver: bridge
